## Задание по библиотеке NumPy
### Лабораторная работа № 4 по дисциплине "Технологии программирования"
#### Индивидуальное задание: Вариант 3

In [1]:
import numpy as np
size = 85
# Матрица M
M = np.ones((size, size)) * 2 + np.diag(np.arange(1, 170, 2))
print('Матрица M:')
print(M)

Матрица M:
[[  3.   2.   2. ...   2.   2.   2.]
 [  2.   5.   2. ...   2.   2.   2.]
 [  2.   2.   7. ...   2.   2.   2.]
 ...
 [  2.   2.   2. ... 167.   2.   2.]
 [  2.   2.   2. ...   2. 169.   2.]
 [  2.   2.   2. ...   2.   2. 171.]]


In [2]:
# Матрица N
N = np.ones((size, size)) * 4
N[::2, 2::3] = 5
N[1::2, 1::2] = 7
print('Матрица N:')
print(N)

Матрица N:
[[4. 4. 5. ... 4. 5. 4.]
 [4. 7. 4. ... 4. 7. 4.]
 [4. 4. 5. ... 4. 5. 4.]
 ...
 [4. 4. 5. ... 4. 5. 4.]
 [4. 7. 4. ... 4. 7. 4.]
 [4. 4. 5. ... 4. 5. 4.]]


In [3]:
# p = {1 + pi: pi ∼ N (2, 4)}
p = 1 + np.random.normal(2, 4, size=size)
print('Вектор p:')
print(p)

Вектор p:
[ 3.51273964 -1.62154659  5.66789462  8.00799721 -0.04446484  6.6860269
 -0.61760469  5.17200838  0.04475313 -0.77787642  8.5054754   2.06300522
  5.33587528  0.39567279  5.6016656   2.2144417  10.00431765  1.06053006
  2.29286267  2.82115521  6.92603926  3.88804524  2.06217288  1.41084055
  6.90289207  5.66311827 -0.18355905 -2.11763652 -3.61355825  0.52773691
  2.48793475  2.35587031  4.51071764 -1.27663654 -2.00811103  5.19276973
 -5.81356992  1.32274911 -1.85619001  9.68304968  7.84525236  4.41918659
  3.29160353  6.0509989   3.76676009 -1.89173538 10.61744184  1.86003516
  4.27523685  7.92744993 -0.36757761  3.54642591 -0.2198221  -0.23586662
 -3.52502458  1.28946495  2.67951111  7.5001423   5.13893768  8.70789094
  3.51721901 -0.61392764 -3.97784719 -0.31395771  5.48244852  2.47016873
  2.54398998  9.32455044  6.24661912 10.44706299  0.65733601  4.33167452
 -2.899601    4.48174962  4.45141541  4.68051491 -0.44461397 10.41487756
  4.66445162  7.86165784  8.9800487   4.98

In [4]:
# q^T = {N24,j ⊙ N71,j}
qT = np.multiply(N[24, :size],N[71, :size])
print('Вектор q^T:')
print(qT)

q = qT.T
print('\nВектор q:')
print(qT)

Вектор q^T:
[16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35.
 16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35.
 16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35.
 16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35.
 16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35. 16.]

Вектор q:
[16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35.
 16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35.
 16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35.
 16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35.
 16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35. 16.]


In [5]:
# Вычисление f = det(qq^T)p
# Вычисляем произведение qq^T
qqT = np.outer(q, qT)
print('qqT:')
print(qqT)

# Вычисляем определитель матрицы det(qq^T)
det_qqT = np.linalg.det(qqT)
print('\ndet_qqT:')
print(det_qqT)

# Вычисляем f
f = det_qqT * p

# Выводим результат
print('\nВектора f:')
print(f)

f = det_qqT
print('\nВектор f:')
print(f)

qqT:
[[ 256.  448.  320. ...  256.  560.  256.]
 [ 448.  784.  560. ...  448.  980.  448.]
 [ 320.  560.  400. ...  320.  700.  320.]
 ...
 [ 256.  448.  320. ...  256.  560.  256.]
 [ 560.  980.  700. ...  560. 1225.  560.]
 [ 256.  448.  320. ...  256.  560.  256.]]

det_qqT:
0.0

Вектора f:
[ 0. -0.  0.  0. -0.  0. -0.  0.  0. -0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0. -0. -0. -0.  0.  0.  0.  0. -0. -0.  0.
 -0.  0. -0.  0.  0.  0.  0.  0.  0. -0.  0.  0.  0.  0. -0.  0. -0. -0.
 -0.  0.  0.  0.  0.  0.  0. -0. -0. -0.  0.  0.  0.  0.  0.  0.  0.  0.
 -0.  0.  0.  0. -0.  0.  0.  0.  0.  0.  0.  0.  0.]

Вектор f:
0.0


In [6]:
# Создаем диагональную матрицу Mii
Mii = np.diag(M)
print('Mii:')
print(Mii)

# Создаем диагональную матрицу Nii
Nii = np.diag(N)
print('\nNii:')
print(Nii)

# Считаем q^Tq
qTq = np.multiply(qT, q)
print('\nqTq:')
print(qTq)

# Считаем разность Mii - Nii
diff = Mii - Nii
print('\ndiff:')
print(diff)

# Вычисляем {Mii-Nii+q^Tq}
result = diff + qTq
print('\nresult:')
print(result)

# Вычисляем g как норму вектора result
g = np.linalg.norm(result, ord=2) # ||...||2 - нормаль вектора
print('\nВектор g:')
print(g)

Mii:
[  3.   5.   7.   9.  11.  13.  15.  17.  19.  21.  23.  25.  27.  29.
  31.  33.  35.  37.  39.  41.  43.  45.  47.  49.  51.  53.  55.  57.
  59.  61.  63.  65.  67.  69.  71.  73.  75.  77.  79.  81.  83.  85.
  87.  89.  91.  93.  95.  97.  99. 101. 103. 105. 107. 109. 111. 113.
 115. 117. 119. 121. 123. 125. 127. 129. 131. 133. 135. 137. 139. 141.
 143. 145. 147. 149. 151. 153. 155. 157. 159. 161. 163. 165. 167. 169.
 171.]

Nii:
[4. 7. 5. 7. 4. 7. 4. 7. 5. 7. 4. 7. 4. 7. 5. 7. 4. 7. 4. 7. 5. 7. 4. 7.
 4. 7. 5. 7. 4. 7. 4. 7. 5. 7. 4. 7. 4. 7. 5. 7. 4. 7. 4. 7. 5. 7. 4. 7.
 4. 7. 5. 7. 4. 7. 4. 7. 5. 7. 4. 7. 4. 7. 5. 7. 4. 7. 4. 7. 5. 7. 4. 7.
 4. 7. 5. 7. 4. 7. 4. 7. 5. 7. 4. 7. 4.]

qTq:
[ 256.  784.  400.  784.  256. 1225.  256.  784.  400.  784.  256. 1225.
  256.  784.  400.  784.  256. 1225.  256.  784.  400.  784.  256. 1225.
  256.  784.  400.  784.  256. 1225.  256.  784.  400.  784.  256. 1225.
  256.  784.  400.  784.  256. 1225.  256.  784.  400.  784.  256. 1225