## Задание по библиотеке NumPy
### Лабораторная работа № 4 по дисциплине "Технологии программирования"
#### Индивидуальное задание: Вариант 3

In [164]:
import numpy as np
size = 85
# Матрица M
M = np.ones((size, size)) * 2 + np.diag(np.arange(1, 170, 2))
print('Матрица M:')
print(M)

Матрица M:
[[  3.   2.   2. ...   2.   2.   2.]
 [  2.   5.   2. ...   2.   2.   2.]
 [  2.   2.   7. ...   2.   2.   2.]
 ...
 [  2.   2.   2. ... 167.   2.   2.]
 [  2.   2.   2. ...   2. 169.   2.]
 [  2.   2.   2. ...   2.   2. 171.]]


In [165]:
# Матрица N
N = np.ones((size, size)) * 4
N[::2, 2::3] = 5
N[1::2, 1::2] = 7
print('Матрица N:')
print(N)

Матрица N:
[[4. 4. 5. ... 4. 5. 4.]
 [4. 7. 4. ... 4. 7. 4.]
 [4. 4. 5. ... 4. 5. 4.]
 ...
 [4. 4. 5. ... 4. 5. 4.]
 [4. 7. 4. ... 4. 7. 4.]
 [4. 4. 5. ... 4. 5. 4.]]


In [166]:
# p = {1 + pi: pi ∼ N (2, 4)}
p = 1 + np.random.normal(2, 4, size=size)
print('Вектор p:')
print(p)

Вектор p:
[ 2.11446575  9.13667719  5.32021241 -0.91032366  1.37765872  3.51895472
 -3.85775144  9.10895448  0.27494205  3.25529469  1.2099702   3.62119503
  6.47931755  6.06588677  6.78245802  6.26197953  1.21010918  1.56485241
  2.78876425  2.24281954  8.13603801  3.79296101 11.17982761  4.46750778
  1.86061795  5.60713456  6.48360869  7.94826837  4.8981655   5.22594203
  9.13246976  1.9774553   5.88548917  3.6280068   8.8073148   4.18831281
  5.43318276  2.49886143  0.44257405  4.86526001  0.16130293  6.4106272
  2.92592177  9.0149111   5.44783139 -2.53345161  1.36962051  2.96690051
 -3.66547599  4.80907182  3.48892455  2.59486217  1.94129103  0.16337914
  8.46978271  5.89567621  3.20204615  5.24553993  5.2709979   1.93866154
  6.67805444 -1.31676853 -3.09105484 -3.51828126 -1.37666589 -0.69348204
 -0.85802061  3.31394955  1.58805119  8.3529139   3.41568759 -1.92931815
 -2.13734909  9.19841124  1.54467356  6.53873249  2.09010776 13.62001995
 -1.60211303  2.48178107 -4.15186745 -0.52

In [167]:
# q^T = {N24,j ⊙ N71,j}
q = np.multiply(n[24, :size],n[71, :size])
print('Вектор q:')
print(q)

Вектор q:
[16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35.
 16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35.
 16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35.
 16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35.
 16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35. 16.]


In [170]:
# Вычисление f = det(qq^T)p
# Вычисляем произведение qq^T
qqT = np.outer(q, q**2).T

# Вычисляем определитель матрицы qq^T
det_qqT = np.linalg.det(qqT)

# Вычисляем f
f = det_qqT * p

# Выводим результат
print('Вектора f:')
print(f)

f = det_qqT
print('\nВектор f:')
print(f)

Вектора f:
[ 0.  0.  0. -0.  0.  0. -0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0. -0.  0.  0. -0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0. -0. -0. -0. -0. -0. -0.  0.  0.  0.  0. -0.
 -0.  0.  0.  0.  0.  0. -0.  0. -0. -0. -0.  0.  0.]

Вектор f:
0.0


In [174]:
# Создаем диагональную матрицу Mii
Mii = np.diag(M)

# Создаем диагональную матрицу Nii
Nii = np.diag(N)

# Считаем q^Tq
qTq = np.outer(q**2, q).T

# Считаем разность Mii - Nii
diff = Mii - Nii

# Вычисляем {Mii-Nii+q^Tq}^84, где q^T(^84) = {N24,j ⊙ N71,j}^84. Метод np.outer - не подходит, т.к. при произведении двух векторов создается
# множество новых элементов!
# Вычисление оставил для проверки
result = diff + qTq

print('\nРезультаты g (со сложением):')
print(result)

# Вычисляем g как норму вектора result
g = np.linalg.norm(result, ord=2) # ||...||2 - нормаль вектора
print('\nВектор g (со сложением):')
print(g)

#Без сложения двух векторов
result = diff + q**2 * q

print('\nРезультаты g:')
print(result)

# Вычисляем g как норму вектора result
g = np.linalg.norm(result, ord=2) # ||...||2 - нормаль вектора
print('\nВектор g:')
print(g)


Результаты g (со сложением):
[[ 4095. 12542.  6402. ...  4259. 19762.  4263.]
 [ 7167. 21950. 11202. ...  7331. 34462.  7335.]
 [ 5119. 15678.  8002. ...  5283. 24662.  5287.]
 ...
 [ 4095. 12542.  6402. ...  4259. 19762.  4263.]
 [ 8959. 27438. 14002. ...  9123. 43037.  9127.]
 [ 4095. 12542.  6402. ...  4259. 19762.  4263.]]

Вектор g (со сложением):
1491694.1873989636

Результаты g:
[ 4095. 21950.  8002. 21954.  4103. 42881.  4107. 21962.  8014. 21966.
  4115. 42893.  4119. 21974.  8026. 21978.  4127. 42905.  4131. 21986.
  8038. 21990.  4139. 42917.  4143. 21998.  8050. 22002.  4151. 42929.
  4155. 22010.  8062. 22014.  4163. 42941.  4167. 22022.  8074. 22026.
  4175. 42953.  4179. 22034.  8086. 22038.  4187. 42965.  4191. 22046.
  8098. 22050.  4199. 42977.  4203. 22058.  8110. 22062.  4211. 42989.
  4215. 22070.  8122. 22074.  4223. 43001.  4227. 22082.  8134. 22086.
  4235. 43013.  4239. 22094.  8146. 22098.  4247. 43025.  4251. 22106.
  8158. 22110.  4259. 43037.  4263.]

Вект