## Задание по библиотеке NumPy
### Лабораторная работа № 4 по дисциплине "Технологии программирования"
#### Индивидуальное задание: Вариант 3

In [1]:
import numpy as np
size = 85
# Матрица M
M = np.ones((size, size)) * 2 + np.diag(np.arange(1, 170, 2))
print('Матрица M:')
print(M)

Матрица M:
[[  3.   2.   2. ...   2.   2.   2.]
 [  2.   5.   2. ...   2.   2.   2.]
 [  2.   2.   7. ...   2.   2.   2.]
 ...
 [  2.   2.   2. ... 167.   2.   2.]
 [  2.   2.   2. ...   2. 169.   2.]
 [  2.   2.   2. ...   2.   2. 171.]]


In [2]:
# Матрица N
N = np.ones((size, size)) * 4
N[::2, 2::3] = 5
N[1::2, 1::2] = 7
print('Матрица N:')
print(N)

Матрица N:
[[4. 4. 5. ... 4. 5. 4.]
 [4. 7. 4. ... 4. 7. 4.]
 [4. 4. 5. ... 4. 5. 4.]
 ...
 [4. 4. 5. ... 4. 5. 4.]
 [4. 7. 4. ... 4. 7. 4.]
 [4. 4. 5. ... 4. 5. 4.]]


In [3]:
# p = {1 + pi: pi ∼ N (2, 4)}^84, i=0: {0, ..., 84}
mx = 2
variance = 4
p = 1 + np.random.normal(mx, variance, size=size)
print('Вектор p:')
print(p)

Вектор p:
[ 0.25845132 -3.80823069  7.43216143  7.09484544 -0.14645322  3.65350653
  3.60481126  0.53937394  5.34790602  2.80711258  8.02904589  4.96492363
 10.65769388  7.65787788 -5.60693367  0.93873531  6.271108    0.62930542
  8.35880137 -1.28654215  4.28934651  2.36771036  5.55305851  7.91748559
  1.30050548 -1.07712024 -1.32496649  4.34787157  0.90289611  3.23768647
 10.72275975 -0.81274443  3.95800078  1.29230974  0.14908659  6.31095108
  3.58410131 -2.98794455 -0.14322955  3.08769696  0.10183965 10.04470072
 -1.47073742  5.21179188  8.13039709  0.96648446  9.47987367  6.74495559
 10.20043652  1.2343463  -0.44548921  1.57235521  3.41391188  1.33194052
  7.62109481  1.88444267  3.26786374  0.83849308  1.43817858  1.61477525
 -0.22769042  6.06959546  3.31076415  5.84565296 10.65795246  1.49306149
 -0.61347165  9.71904879  2.33628553 -5.25199613 -3.64050495  0.49507118
 -2.17169186 -0.210463    8.079487    4.43983657 -3.05582106  0.7387359
  2.36122873  3.64026251  0.80572247  7.59

In [4]:
# q^T = {N24,j ⊙ N71,j}^84, j=0: {0, ..., 84}
qT = np.multiply(N[24, :size],N[71, :size])
print('Вектор q^T:')
print(qT)

q = qT.T
print('\nВектор q:')
print(q)

Вектор q^T:
[16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35.
 16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35.
 16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35.
 16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35.
 16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35. 16.]

Вектор q:
[16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35.
 16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35.
 16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35.
 16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35.
 16. 28. 20. 28. 16. 35. 16. 28. 20. 28. 16. 35. 16.]


In [5]:
# Вычисление f = det(qq^T)p
# Вычисляем произведение qq^T
qqT = np.outer(q, qT)
print('qqT:')
print(qqT)

# Вычисляем определитель матрицы det(qq^T)
det_qqT = np.linalg.det(qqT)
print('\ndet_qqT:')
print(det_qqT)

# Вычисляем f
f = det_qqT * p

# Выводим результат
print('\nВектора f:')
print(f)

f = det_qqT
print('\nВектор f:')
print(f)

qqT:
[[ 256.  448.  320. ...  256.  560.  256.]
 [ 448.  784.  560. ...  448.  980.  448.]
 [ 320.  560.  400. ...  320.  700.  320.]
 ...
 [ 256.  448.  320. ...  256.  560.  256.]
 [ 560.  980.  700. ...  560. 1225.  560.]
 [ 256.  448.  320. ...  256.  560.  256.]]

det_qqT:
0.0

Вектора f:
[ 0. -0.  0.  0. -0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -0.  0.  0.  0.
  0. -0.  0.  0.  0.  0.  0. -0. -0.  0.  0.  0.  0. -0.  0.  0.  0.  0.
  0. -0. -0.  0.  0.  0. -0.  0.  0.  0.  0.  0.  0.  0. -0.  0.  0.  0.
  0.  0.  0.  0.  0.  0. -0.  0.  0.  0.  0.  0. -0.  0.  0. -0. -0.  0.
 -0. -0.  0.  0. -0.  0.  0.  0.  0.  0.  0.  0.  0.]

Вектор f:
0.0


In [6]:
# Вычисление g = ||{M_(ii) - N_(ii) + q^Tq}^84 ||_2 , где i = 0: {0, ..., 84}
# Создаем диагональную матрицу Mii
Mii = np.diag(M)
print('Mii:')
print(Mii)

# Создаем диагональную матрицу Nii
Nii = np.diag(N)
print('\nNii:')
print(Nii)

# Считаем q^Tq
qTq = np.multiply(qT, q)
print('\nqTq:')
print(qTq)

# Считаем разность Mii - Nii
diff = Mii - Nii
print('\ndiff:')
print(diff)

# Вычисляем {Mii-Nii+q^Tq}
result = diff + qTq
print('\nresult:')
print(result)

# Вычисляем g как норму вектора result
g = np.linalg.norm(result, ord=2) # ||...||2 - нормаль вектора
print('\nВектор g:')
print(g)

Mii:
[  3.   5.   7.   9.  11.  13.  15.  17.  19.  21.  23.  25.  27.  29.
  31.  33.  35.  37.  39.  41.  43.  45.  47.  49.  51.  53.  55.  57.
  59.  61.  63.  65.  67.  69.  71.  73.  75.  77.  79.  81.  83.  85.
  87.  89.  91.  93.  95.  97.  99. 101. 103. 105. 107. 109. 111. 113.
 115. 117. 119. 121. 123. 125. 127. 129. 131. 133. 135. 137. 139. 141.
 143. 145. 147. 149. 151. 153. 155. 157. 159. 161. 163. 165. 167. 169.
 171.]

Nii:
[4. 7. 5. 7. 4. 7. 4. 7. 5. 7. 4. 7. 4. 7. 5. 7. 4. 7. 4. 7. 5. 7. 4. 7.
 4. 7. 5. 7. 4. 7. 4. 7. 5. 7. 4. 7. 4. 7. 5. 7. 4. 7. 4. 7. 5. 7. 4. 7.
 4. 7. 5. 7. 4. 7. 4. 7. 5. 7. 4. 7. 4. 7. 5. 7. 4. 7. 4. 7. 5. 7. 4. 7.
 4. 7. 5. 7. 4. 7. 4. 7. 5. 7. 4. 7. 4.]

qTq:
[ 256.  784.  400.  784.  256. 1225.  256.  784.  400.  784.  256. 1225.
  256.  784.  400.  784.  256. 1225.  256.  784.  400.  784.  256. 1225.
  256.  784.  400.  784.  256. 1225.  256.  784.  400.  784.  256. 1225.
  256.  784.  400.  784.  256. 1225.  256.  784.  400.  784.  256. 1225